### ISSUE TITLE
TairSearch#tftdeldoc存在类型转换异常100%必现

### ISSUE THREAD

**Issue by 605910034** [tair-opensource/alibabacloud-tairjedis-sdk#29]
3.0.6版本中：
com.aliyun.tair.tairsearch.TairSearch#tftdeldoc(java.lang.String, java.lang.String...)此方法存在ClassCastException
参数转换异常
原因定位：操作成功返回的为long型数字，无法转换为byte[]。
<img width="824" alt="image" src="https://github.com/tair-opensource/alibabacloud-tairjedis-sdk/assets/21071479/fb41cda4-d6cc-4c18-89e3-51aa3c471cc2">
<img width="945" alt="image" src="https://github.com/tair-opensource/alibabacloud-tairjedis-sdk/assets/21071479/d330c9da-0ac5-480d-b937-e955002786e0">

**Comment by yangbodong22011** [comment]
收到，我们尽快确认修复。

**Comment by yangbodong22011** [comment]
您好，此问题后续的修复方案将在阿里云工单同步给您。
